services:
    app:
      container_name: ecoride-app
      build: .
      volumes: 
        - ./:/var/www/html:cached
        - ./docker/config/default.conf:/etc/apache2/sites-available/000-default.conf:ro
        - user_photos:/var/www/html/photos
      ports:
         - 8080:80
      environment:
        DB_HOST: db
        DB_PORT: 3306
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        MONGO_URI: ${MONGO_URI}
        MONGO_DB: ${MONGO_DB}
      depends_on:
        db:
            condition: service_healthy
        mongo:
          condition: service_healthy
    
    db:
      image: mysql:8.0
      container_name: ecoride-db
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
      ports:
        - "3307:3306"
      volumes:
        - db_data:/var/lib/mysql 
      healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"]
        interval: 5s
        timeout: 3s
        retries: 30
    phpmyadmin:
      image: phpmyadmin:5.2.2
      container_name: ecoride-phpmyadmin
      environment:
        PMA_HOST: db
        PMA_USER: ${DB_USER}
        PMA_PASSWORD: ${DB_PASS}
      ports:
        - "8081:80"

    mongo:
      image: mongo:7
      container_name: ecoride-mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
        MONGO_INITDB_DATABASE: ${MONGO_DB}
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      healthcheck:
        test: ["CMD-SHELL", "mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --eval 'db.adminCommand({ ping: 1 })' --authenticationDatabase admin || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 30

    mongo-express:
      image: mongo-express:1.0.2
      container_name: ecoride-mongo-express
      depends_on:
        - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASIC_USER}
        ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASIC_PASS}
      ports:
        - "8082:8081"
      restart: unless-stopped

volumes:
  db_data:
  mongo_data:
  user_photos: